### ISSUE TITLE
Can we use GitHub as a forum?

### ISSUE THREAD

**Issue by rosehartman** [InteragencyEcologicalProgram/Status-and-Trends#2]
Some folks at DWR are into Slack, but apparently USFWS can't use Slack. I'm testing this out... reply if you think it's  a good idea.

**Comment by vdtobias** [comment]
I can see this working. I had been watching this repo so I got an email notice that the issue was posted. That would make it pretty easy for people to make sure that the see and respond to questions.

**Comment by OneGneissGuy** [comment]
I saw it easily enough. How easy is it to respond to, though? As easy as an
email/text?

**Comment by vdtobias** [comment]
It seems pretty easy. I replied via GitHub directly the first time, but I'm
using email this time.

**Comment by vdtobias** [comment]
Ooh. Ok, maybe I should have deleted all that quoted text before I responded.
