### ISSUE TITLE
publishing the ebook

### ISSUE THREAD

**Issue by rosehartman** [InteragencyEcologicalProgram/Status-and-Trends#23]
I’ve spend most of the day trying to get the Spring Report into an HTML version. I thought I had everything organized nicely (or at least a first draft), so I tried to “deploy” the book, and had it fail miserably. I tried publishing it to GitHub pages
https://interagencyecologicalprogram.github.io/Status-and-Trends/

and to bookdown.org
https://bookdown.org/connect/#/apps/3988/access

But all of my pictures disappear! I don’t know what I’m doing wrong. Help!

**Comment by mkoohafkan** [comment]
Will start investigating, but at first glance it looks like a problem with how the figure paths are defined in the book.

**Comment by rosehartman** [comment]
I would assume the same thing, except some of the figures worked and others didn't!! And all the figures are in the same place! 

I'm probably misplacing a comma somewhere. Or the coronavisrus has infected my code.

**Comment by mkoohafkan** [comment]
take a look at https://github.com/InteragencyEcologicalProgram/Status-and-Trends/blob/e3304efe10fecf04814d4566bfeef331b6758c2e/spring_report/report_bookdown/index.Rmd#L19

You are defining a relative figure path that steps to the directory **above** the main directory and references the figures folder there. This propagates to the html files generated by bookdown, as you can see here https://github.com/InteragencyEcologicalProgram/Status-and-Trends/blob/c00723c9c0182f28506cc4bc8f4871411fcbd1fa/spring_report/report_bookdown/_book/index.html#L141

The solution is to have the figures folder live in the bookdown directory, which will allow relative paths to work. It looks like you already have a [figures folder in the right place](https://github.com/InteragencyEcologicalProgram/Status-and-Trends/tree/master/spring_report/report_bookdown/figures), but you're instead referring to a [figures folder in the parent directory](https://github.com/InteragencyEcologicalProgram/Status-and-Trends/tree/master/spring_report/report_bookdown/figures).

**Comment by mkoohafkan** [comment]
The exception that proves the rule is https://github.com/InteragencyEcologicalProgram/Status-and-Trends/blob/65206c883da223f06d5a9b98a94dfd21a4cd815e/spring_report/report_bookdown/02-temperature.Rmd#L28

This image is linking to `figures/` and shows up, whereas images that link to `../figures/` don't show up.

**Comment by rosehartman** [comment]
WEll, I feel dumb. I was copying and pasting from Lara without actually knowing what I was doing. Thanks so much for helping me out!

**Comment by mkoohafkan** [comment]
Nah, bookdown is really finicky on it's own and then using publishing services like gh-pages adds another level of complexity because the directory structure changes behind-the-scenes. One thing that can help debug is to look at the actual HTML outputs produced by bookdown or viewing the source code of the published web page to see what's going on.

I say this from hours and hours of "experience" debugging bookdown books, of which ~70% was just banging my head against the wall.
