### ISSUE TITLE
Fish picture formatting

### ISSUE THREAD

**Issue by rosehartman** [InteragencyEcologicalProgram/Status-and-Trends#26]
If anyone has time to play with Markdown, I"m having trouble getting the fish pictures above the graphs to be formatted right. I'd like them all to be a consistent size so the graphs below them line up. Any hints?

**Comment by lmitchell4** [comment]
I put the fish pictures and graphs in separate rows. It might be better if
the fish pictures are centered vertically in their rows but that can be
tricky and I don't have it working yet.

It looks like there are some problems in the Winter Fish section
(inconsistencies between the background section, pictures, and graphs).

Lara

**Comment by rosehartman** [comment]
THANK YOU!!! And yes, I"ve been working through the winter report to make the graphs match.
