### ISSUE TITLE
GitHub Pages not building

### ISSUE THREAD

**Issue by rosehartman** [InteragencyEcologicalProgram/Status-and-Trends#34]
With Lara's new organization we no longer have a "docs" folder. For reasons that are beyond me, GitHub pages will only build the page from teh "docs" folder or the main folder of the repo. Would there be any reason we can't rename the "report" folder "docs"? Or does anyone know another way around this?

**Comment by lmitchell4** [comment]
Hmm let me try something on GitHub ....

**Comment by lmitchell4** [comment]
Yep, you're right, it has to be called docs. I guess we can rename it back to docs!

**Comment by rosehartman** [comment]
I renamed it "docs". I don't know why it's so silly like that.
